In [1]:
import pandas as pd
import numpy as np

In [2]:
team_arr = []
tids = np.arange(30)
tids = tids + 1610612737
for tid in tids:
    team = teamyearbyyearstats.TeamYearByYearStats(team_id = tid)
    team_arr.append(team.get_data_frames())

NameError: name 'teamyearbyyearstats' is not defined

In [3]:
team_concat = pd.concat(team_arr, axis = 1)

ValueError: No objects to concatenate

Below code creates a list of dataframes where each individual one is a single team.

In [125]:
from nba_api.stats.endpoints import teamyearbyyearstats
team_id = 1610612737
team_arr = []
for i in range(30):
    team = teamyearbyyearstats.TeamYearByYearStats(team_id+i, timeout=500)
    team_arr.append([team.get_data_frames()[0]])
team_arr[0]

[       TEAM_ID   TEAM_CITY   TEAM_NAME     YEAR  GP  WINS  LOSSES  WIN_PCT  \
 0   1610612737  Tri-Cities  Blackhawks  1949-50  64    29      35    0.453
 1   1610612737  Tri-Cities  Blackhawks  1950-51  68    25      43    0.368
 2   1610612737   Milwaukee       Hawks  1951-52  66    17      49    0.258
 3   1610612737   Milwaukee       Hawks  1952-53  71    27      44    0.380
 4   1610612737   Milwaukee       Hawks  1953-54  72    21      51    0.292
 5   1610612737   Milwaukee       Hawks  1954-55  72    26      46    0.361
 6   1610612737   St. Louis       Hawks  1955-56  72    33      39    0.458
 7   1610612737   St. Louis       Hawks  1956-57  72    34      38    0.472
 8   1610612737   St. Louis       Hawks  1957-58  72    41      31    0.569
 9   1610612737   St. Louis       Hawks  1958-59  72    49      23    0.681
 10  1610612737   St. Louis       Hawks  1959-60  75    46      29    0.613
 11  1610612737   St. Louis       Hawks  1960-61  79    51      28    0.646
 12  1610612737   St. Louis       Hawks  1961-62  80    29      51    0.363
 13  1610612737   St. Louis       Hawks  1962-63  80    48      32    0.600
 14  1610612737   St. Louis       Hawks  1963-64  80    46      34    0.575
 15  1610612737   St. Louis       Hawks  1964-65  80    45      35    0.563
 16  1610612737   St. Louis       Hawks  1965-66  80    36      44    0.450
 17  1610612737   St. Louis       Hawks  1966-67  81    39      42    0.481
 18  1610612737   St. Louis       Hawks  1967-68  82    56      26    0.683
 19  1610612737     Atlanta       Hawks  1968-69  82    48      34    0.585
 20  1610612737     Atlanta       Hawks  1969-70  82    48      34    0.585
 21  1610612737     Atlanta       Hawks  1970-71  82    36      46    0.439
 22  1610612737     Atlanta       Hawks  1971-72  82    36      46    0.439
 23  1610612737     Atlanta       Hawks  1972-73  82    46      36    0.561
 24  1610612737     Atlanta       Hawks  1973-74  82    35      47    0.427
 25  1610612737     Atlanta       Hawks  1974-75  82    31      51    0.378
 26  1610612737     Atlanta       Hawks  1975-76  82    29      53    0.354
 27  1610612737     Atlanta       Hawks  1976-77  82    31      51    0.378
 28  1610612737     Atlanta       Hawks  1977-78  82    41      41    0.500
 29  1610612737     Atlanta       Hawks  1978-79  82    46      36    0.561
 ..         ...         ...         ...      ...  ..   ...     ...      ...
 40  1610612737     Atlanta       Hawks  1989-90  82    41      41    0.500
 41  1610612737     Atlanta       Hawks  1990-91  82    43      39    0.524
 42  1610612737     Atlanta       Hawks  1991-92  82    38      44    0.463
 43  1610612737     Atlanta       Hawks  1992-93  82    43      39    0.524
 44  1610612737     Atlanta       Hawks  1993-94  82    57      25    0.695
 45  1610612737     Atlanta       Hawks  1994-95  82    42      40    0.512
 46  1610612737     Atlanta       Hawks  1995-96  82    46      36    0.561
 47  1610612737     Atlanta       Hawks  1996-97  82    56      26    0.683
 48  1610612737     Atlanta       Hawks  1997-98  82    50      32    0.610
 49  1610612737     Atlanta       Hawks  1998-99  50    31      19    0.620
 50  1610612737     Atlanta       Hawks  1999-00  82    28      54    0.341
 51  1610612737     Atlanta       Hawks  2000-01  82    25      57    0.305
 52  1610612737     Atlanta       Hawks  2001-02  82    33      49    0.402
 53  1610612737     Atlanta       Hawks  2002-03  82    35      47    0.427
 54  1610612737     Atlanta       Hawks  2003-04  82    28      54    0.341
 55  1610612737     Atlanta       Hawks  2004-05  82    13      69    0.159
 56  1610612737     Atlanta       Hawks  2005-06  82    26      56    0.317
 57  1610612737     Atlanta       Hawks  2006-07  82    30      52    0.366
 58  1610612737     Atlanta       Hawks  2007-08  82    37      45    0.451
 59  1610612737     Atlanta       Hawks  2008-09  82    47      35    0.573
 60  1610612737     Atlanta       Hawks  2009-10  82    53      29    0.646
 61  1610612737     Atlanta       Hawks  2010-11  82    44      38    0.537
 62  1610612737     Atlanta       Hawks  2011-12  66    40      26    0.606
 63  1610612737     Atlanta       Hawks  2012-13  82    44      38    0.537
 64  1610612737     Atlanta       Hawks  2013-14  82    38      44    0.463
 65  1610612737     Atlanta       Hawks  2014-15  82    60      22    0.732
 66  1610612737     Atlanta       Hawks  2015-16  82    48      34    0.585
 67  1610612737     Atlanta       Hawks  2016-17  82    43      39    0.524
 68  1610612737     Atlanta       Hawks  2017-18  82    24      58    0.293
 69  1610612737     Atlanta       Hawks  2018-19  82    29      53    0.354

     CONF_RANK  DIV_RANK  ...  OREB  DREB   REB   AST    PF  STL   TOV  BLK  \
 0           0         3  ...     0     0     0  1330  2057    0     0    0
 1           0         5  ...     0     0     0  1476  2092    0     0    0
 2           0         5  ...     0     0     0  1229  1848    0     0    0
 3           0         5  ...     0     0     0  1427  2120    0     0    0
 4           0         4  ...     0     0     0  1298  1771    0     0    0
 5           0         4  ...     0     0     0  1544  1904    0     0    0
 6           0         2  ...     0     0     0  1748  1971    0     0    0
 7           0         1  ...     0     0     0  1454  1848    0     0    0
 8           0         1  ...     0     0     0  1541  1875    0     0    0
 9           0         1  ...     0     0     0  1567  1937    0     0    0
 10          0         1  ...     0     0     0  1881  1995    0     0    0
 11          0         1  ...     0     0     0  2136  2135    0     0    0
 12          0         4  ...     0     0     0  1996  2166    0     0    0
 13          0         2  ...     0     0     0  1902  2077    0     0    0
 14          0         2  ...     0     0     0  1901  2266    0     0    0
 15          0         2  ...     0     0     0  1691  2069    0     0    0
 16          0         3  ...     0     0     0  1782  2179    0     0    0
 17          0         2  ...     0     0     0  1708  2173    0     0    0
 18          0         1  ...     0     0     0  1988  2046    0     0    0
 19          0         2  ...     0     0     0  2069  2082    0     0    0
 20          0         1  ...     0     0     0  2142  2016    0     0    0
 21          4         2  ...     0     0     0  1906  1958    0     0    0
 22          4         2  ...     0     0     0  1897  1967    0     0    0
 23          4         2  ...     0     0     0  2074  1916    0     0    0
 24          5         2  ...  1240  2712  3952  1993  2073  758  1823  332
 25          8         4  ...  1441  2653  4094  1878  1964  744  1550  227
 26          9         5  ...  1225  2540  3765  1666  1983  790  1553  277
 27          9         6  ...  1244  2512  3756  1882  2302  733  1779  330
 28          6         4  ...  1160  2359  3519  1901  2470  916  1592  408
 29          5         3  ...  1381  2341  3722  1938  2424  801  1523  596
 ..        ...       ...  ...   ...   ...   ...   ...   ...  ...   ...  ...
 40          9         6  ...  1273  2187  3460  1820  1871  717  1270  353
 41          6         4  ...  1235  2420  3655  1864  1768  729  1231  374
 42          8         5  ...  1288  2498  3786  2123  1771  793  1255  320
 43          6         4  ...  1290  2344  3634  2084  1807  806  1339  278
 44          1         1  ...  1250  2423  3673  2056  1625  915  1252  449
 45          7         5  ...  1104  2272  3376  1757  1804  738  1221  412
 46          6         4  ...  1182  2148  3330  1609  1714  771  1228  319
 47          4         2  ...  1021  2350  3371  1557  1591  701  1228  427
 48          5         4  ...  1106  2417  3523  1569  1671  653  1214  491
 49          4         2  ...   676  1499  2175   782   987  346   745  260
 50         14         7  ...  1146  2570  3716  1548  1718  500  1266  461
 51         13         7  ...  1028  2490  3518  1559  1863  634  1368  387
 52         12         6  ...   955  2445  3400  1656  1702  667  1275  350
 53         11         5  ...   937  2558  3495  1679  1783  611  1367  473
 54         12         7  ...   996  2507  3503  1648  1826  627  1350  408
 55         15         5  ...  1100  2335  3435  1614  2009  629  1319  344
 56         14         5  ...  1069  2232  3301  1625  2054  587  1284  394
 57         13         5  ...   976  2312  3288  1573  1970  609  1306  446
 58          8         3  ...  1008  2454  3462  1804  1673  600  1223  448
 59          4         2  ...   870  2412  3282  1657  1610  603  1048  376
 60          3         2  ...   969  2451  3420  1789  1632  592   980  413
 61          5         3  ...   762  2460  3222  1802  1554  497  1118  341
 62          5         2  ...   652  2066  2718  1481  1178  536   921  303
 63          6         2  ...   758  2593  3351  2007  1473  664  1219  369
 64          8         4  ...   713  2565  3278  2041  1577  680  1251  326
 65          1         1  ...   715  2611  3326  2111  1457  744  1167  380
 66          4         2  ...   679  2772  3451  2100  1570  747  1226  486
 67          5         2  ...   842  2793  3635  1938  1491  672  1294  397
 68         15         5  ...   743  2693  3436  1946  1606  638  1274  348
 69         12         5  ...   955  2825  3780  2118  1932  675  1397  419

      PTS  PTS_RANK
 0   5313        10
 1   5730         3
 2   4833        10
 3   5389         9
 4   5038         9
 5   6291         8
 6   6953         6
 7   7091         6
 8   7738         3
 9   7830         4
 10  8506         5
 11  9383         4
 12  9508         5
 13  8766         9
 14  8797         6
 15  8706         6
 16  8913         8
 17  9204         8
 18  9266        10
 19  9123         9
 20  9646         6
 21  9348         8
 22  8982         8
 23  9219         3
 24  8907         5
 25  8620         4
 26  8411        15
 27  8394        19
 28  8506        22
 29  8950        12
 ..   ...       ...
 40  8901        11
 41  9003         8
 42  8711        11
 43  8814         9
 44  8318        11
 45  7921        24
 46  8059        18
 47  7774        23
 48  7860        15
 49  4315        28
 50  7735        25
 51  7459        26
 52  7711        19
 53  7714        18
 54  7611        15
 55  7605        28
 56  7972        16
 57  7680        30
 58  8054        15
 59  8046        19
 60  8338        13
 61  7790        26
 62  6375        17
 63  8032        14
 64  8282        15
 65  8409        10
 66  8433        12
 67  8459        22
 68  8475        25
 69  9294        12

 [70 rows x 34 columns]]

arr is a single dataframe which has each team's data appended to it, so it contains all the team data from every season

In [49]:
arr = pd.DataFrame()
for i in range(30):
    arr = arr.append(team_arr[i][0])
arr

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
0,1610612737,Tri-Cities,Blackhawks,1949-50,64,29,35,0.453,0,3,...,0,0,0,1330,2057,0,0,0,5313,10
1,1610612737,Tri-Cities,Blackhawks,1950-51,68,25,43,0.368,0,5,...,0,0,0,1476,2092,0,0,0,5730,3
2,1610612737,Milwaukee,Hawks,1951-52,66,17,49,0.258,0,5,...,0,0,0,1229,1848,0,0,0,4833,10
3,1610612737,Milwaukee,Hawks,1952-53,71,27,44,0.380,0,5,...,0,0,0,1427,2120,0,0,0,5389,9
4,1610612737,Milwaukee,Hawks,1953-54,72,21,51,0.292,0,4,...,0,0,0,1298,1771,0,0,0,5038,9
5,1610612737,Milwaukee,Hawks,1954-55,72,26,46,0.361,0,4,...,0,0,0,1544,1904,0,0,0,6291,8
6,1610612737,St. Louis,Hawks,1955-56,72,33,39,0.458,0,2,...,0,0,0,1748,1971,0,0,0,6953,6
7,1610612737,St. Louis,Hawks,1956-57,72,34,38,0.472,0,1,...,0,0,0,1454,1848,0,0,0,7091,6
8,1610612737,St. Louis,Hawks,1957-58,72,41,31,0.569,0,1,...,0,0,0,1541,1875,0,0,0,7738,3
9,1610612737,St. Louis,Hawks,1958-59,72,49,23,0.681,0,1,...,0,0,0,1567,1937,0,0,0,7830,4
10,1610612737,St. Louis,Hawks,1959-60,75,46,29,0.613,0,1,...,0,0,0,1881,1995,0,0,0,8506,5
11,1610612737,St. Louis,Hawks,1960-61,79,51,28,0.646,0,1,...,0,0,0,2136,2135,0,0,0,9383,4
12,1610612737,St. Louis,Hawks,1961-62,80,29,51,0.363,0,4,...,0,0,0,1996,2166,0,0,0,9508,5
13,1610612737,St. Louis,Hawks,1962-63,80,48,32,0.600,0,2,...,0,0,0,1902,2077,0,0,0,8766,9
14,1610612737,St. Louis,Hawks,1963-64,80,46,34,0.575,0,2,...,0,0,0,1901,2266,0,0,0,8797,6
15,1610612737,St. Louis,Hawks,1964-65,80,45,35,0.563,0,2,...,0,0,0,1691,2069,0,0,0,8706,6
16,1610612737,St. Louis,Hawks,1965-66,80,36,44,0.450,0,3,...,0,0,0,1782,2179,0,0,0,8913,8
17,1610612737,St. Louis,Hawks,1966-67,81,39,42,0.481,0,2,...,0,0,0,1708,2173,0,0,0,9204,8
18,1610612737,St. Louis,Hawks,1967-68,82,56,26,0.683,0,1,...,0,0,0,1988,2046,0,0,0,9266,10
19,1610612737,Atlanta,Hawks,1968-69,82,48,34,0.585,0,2,...,0,0,0,2069,2082,0,0,0,9123,9
20,1610612737,Atlanta,Hawks,1969-70,82,48,34,0.585,0,1,...,0,0,0,2142,2016,0,0,0,9646,6
21,1610612737,Atlanta,Hawks,1970-71,82,36,46,0.439,4,2,...,0,0,0,1906,1958,0,0,0,9348,8
22,1610612737,Atlanta,Hawks,1971-72,82,36,46,0.439,4,2,...,0,0,0,1897,1967,0,0,0,8982,8
23,1610612737,Atlanta,Hawks,1972-73,82,46,36,0.561,4,2,...,0,0,0,2074,1916,0,0,0,9219,3
24,1610612737,Atlanta,Hawks,1973-74,82,35,47,0.427,5,2,...,1240,2712,3952,1993,2073,758,1823,332,8907,5
25,1610612737,Atlanta,Hawks,1974-75,82,31,51,0.378,8,4,...,1441,2653,4094,1878,1964,744,1550,227,8620,4
26,1610612737,Atlanta,Hawks,1975-76,82,29,53,0.354,9,5,...,1225,2540,3765,1666,1983,790,1553,277,8411,15
27,1610612737,Atlanta,Hawks,1976-77,82,31,51,0.378,9,6,...,1244,2512,3756,1882,2302,733,1779,330,8394,19
28,1610612737,Atlanta,Hawks,1977-78,82,41,41,0.500,6,4,...,1160,2359,3519,1901,2470,916,1592,408,8506,22
29,1610612737,Atlanta,Hawks,1978-79,82,46,36,0.561,5,3,...,1381,2341,3722,1938,2424,801,1523,596,8950,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1610612765,Detroit,Pistons,2018-19,82,41,41,0.500,8,3,...,936,2752,3688,1845,1811,569,1135,331,8778,25
0,1610612766,Charlotte,Hornets,1988-89,82,20,62,0.244,12,6,...,1138,2200,3338,2323,2068,705,1318,264,8566,22
1,1610612766,Charlotte,Hornets,1989-90,82,19,63,0.232,14,7,...,962,2211,3173,2080,1889,778,1226,262,8232,25
2,1610612766,Charlotte,Hornets,1990-91,82,26,56,0.317,11,7,...,1027,2200,3227,2019,1946,759,1290,304,8428,20
3,1610612766,Charlotte,Hornets,1991-92,82,31,51,0.378,11,6,...,1164,2367,3531,2284,1819,822,1273,309,8980,6
4,1610612766,Charlotte,Hornets,1992-93,82,44,38,0.537,5,3,...,1095,2508,3603,2161,1790,639,1325,473,9030,2
5,1610612766,Charlotte,Hornets,1993-94,82,41,41,0.500,9,5,...,1019,2475,3494,2214,1747,724,1266,394,8732,4
6,1610612766,Charlotte,Hornets,1994-95,82,50,32,0.610,4,2,...,832,2395,3227,2072,1685,620,1224,399,8249,15
7,1610612766,Charlotte,Hornets,1995-96,82,41,41,0.500,9,6,...,987,2256,3243,1907,1815,582,1241,277,8431,8
8,1610612766,Charlotte,Hornets,1996-97,82,54,28,0.659,5,3,...,910,2298,3208,2021,1702,597,1203,349,8108,12
9,1610612766,Charlotte,Hornets,1997-98,82,51,31,0.622,4,3,...,985,2341,3326,1941,1757,691,1247,312,7923,10
10,1610612766,Charlotte,Hornets,1998-99,50,26,24,0.520,9,5,...,480,1493,1973,1110,1101,443,796,247,4644,12
11,1610612766,Charlotte,Hornets,1999-00,82,49,33,0.598,4,2,...,884,2635,3519,2023,1670,732,1206,480,8072,14
12,1610612766,Charlotte,Hornets,2000-01,82,46,36,0.561,6,3,...,1033,2608,3641,1900,1753,665,1183,455,7539,24
13,1610612766,Charlotte,Hornets,2001-02,82,44,38,0.537,4,2,...,1059,2505,3564,1759,1747,653,1150,456,7700,20
14,1610612766,Charlotte,Bobcats,2004-05,82,18,64,0.220,14,4,...,1083,2335,3418,1794,1894,695,1192,440,7729,22
15,1610612766,Charlotte,Bobcats,2005-06,82,26,56,0.317,13,4,...,990,2270,3260,1717,1960,822,1167,354,7943,18
16,1610612766,Charlotte,Bobcats,2006-07,82,33,49,0.402,11,4,...,920,2346,3266,1836,1985,638,1224,369,7945,18
17,1610612766,Charlotte,Bobcats,2007-08,82,32,50,0.390,12,4,...,892,2440,3332,1748,1777,614,1204,402,7959,19
18,1610612766,Charlotte,Bobcats,2008-09,82,35,47,0.427,10,4,...,886,2366,3252,1741,1754,580,1279,397,7677,30
19,1610612766,Charlotte,Bobcats,2009-10,82,44,38,0.537,7,4,...,858,2490,3348,1658,1597,632,1290,446,7813,28
20,1610612766,Charlotte,Bobcats,2010-11,82,34,48,0.415,10,4,...,848,2444,3292,1728,1637,524,1192,433,7650,29
21,1610612766,Charlotte,Bobcats,2011-12,66,7,59,0.106,15,5,...,677,1894,2571,1326,1249,397,957,361,5739,30
22,1610612766,Charlotte,Bobcats,2012-13,82,21,61,0.256,14,4,...,917,2389,3306,1587,1561,591,1153,479,7661,26
23,1610612766,Charlotte,Bobcats,2013-14,82,43,39,0.524,7,3,...,776,2724,3500,1778,1493,499,1010,421,7942,23
24,1610612766,Charlotte,Hornets,2014-15,82,33,49,0.402,11,4,...,820,2793,3613,1654,1494,499,976,448,7721,28
25,1610612766,Charlotte,Hornets,2015-16,82,48,34,0.585,6,3,...,734,2869,3603,1778,1487,595,1029,438,8479,11
26,1610612766,Charlotte,Hornets,2016-17,82,36,46,0.439,11,4,...,721,2853,3574,1891,1360,571,942,390,8601,16
27,1610612766,Charlotte,Hornets,2017-18,82,36,46,0.439,10,3,...,827,2901,3728,1770,1409,559,1041,373,8874,10
28,1610612766,Charlotte,Hornets,2018-19,82,39,43,0.476,9,2,...,814,2778,3592,1905,1550,591,1001,405,9081,19

This groups all the data in total data array and gets a group from a single year

In [124]:
arr.groupby(['YEAR']).get_group('1980-81')

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
31,1610612737,Atlanta,Hawks,1980-81,82,31,51,0.378,8,4,...,1201,2224,3425,1846,2276,749,1605,469,8604,19
34,1610612738,Boston,Celtics,1980-81,82,62,20,0.756,1,1,...,1155,2424,3579,2202,1990,683,1577,594,9008,8
10,1610612739,Cleveland,Cavaliers,1980-81,82,28,54,0.341,9,5,...,1258,2243,3501,2007,1995,632,1396,322,8670,17
14,1610612741,Chicago,Bulls,1980-81,82,45,37,0.549,5,2,...,1227,2475,3702,1925,2058,729,1672,514,8937,10
0,1610612742,Dallas,Mavericks,1980-81,82,15,67,0.183,12,6,...,1109,2177,3286,1984,2008,561,1439,214,8322,21
4,1610612743,Denver,Nuggets,1980-81,82,37,45,0.451,8,4,...,1325,2497,3822,2030,2108,720,1444,380,9986,1
34,1610612744,Golden State,Warriors,1980-81,82,39,43,0.476,7,4,...,1403,2366,3769,2026,2158,611,1547,301,9006,9
13,1610612745,Houston,Rockets,1980-81,82,40,42,0.488,5,2,...,1216,2347,3563,2099,1901,705,1451,390,8878,11
10,1610612746,San Diego,Clippers,1980-81,82,36,46,0.439,9,5,...,1169,2144,3313,2098,2078,764,1407,292,8737,16
32,1610612747,Los Angeles,Lakers,1980-81,82,54,28,0.659,3,2,...,1165,2491,3656,2363,1955,808,1557,551,9117,5
12,1610612749,Milwaukee,Bucks,1980-81,82,60,22,0.732,3,1,...,1261,2408,3669,2319,2198,862,1581,530,9276,2
4,1610612751,New Jersey,Nets,1980-81,82,24,58,0.293,10,5,...,1092,2374,3466,2068,2204,750,1664,458,8768,15
34,1610612752,New York,Knicks,1980-81,82,50,32,0.610,4,3,...,1137,2205,3342,1976,1917,861,1461,314,8849,12
4,1610612754,Indiana,Pacers,1980-81,82,44,38,0.537,6,3,...,1325,2267,3592,2091,2006,833,1491,484,8827,13
31,1610612755,Philadelphia,76ers,1980-81,82,62,20,0.756,1,1,...,1091,2618,3709,2369,2061,857,1702,591,9156,4
12,1610612756,Phoenix,Suns,1980-81,82,57,25,0.695,1,1,...,1234,2490,3724,2205,1996,876,1733,416,9019,7
10,1610612757,Portland,Trail Blazers,1980-81,82,45,37,0.549,4,3,...,1243,2388,3631,2244,2034,769,1518,480,9080,6
32,1610612758,Kansas City,Kings,1980-81,82,40,42,0.488,5,2,...,1037,2450,3487,2271,2092,719,1448,385,8769,14
4,1610612759,San Antonio,Spurs,1980-81,82,52,30,0.634,2,1,...,1304,2582,3886,2048,2114,685,1533,643,9209,3
13,1610612760,Seattle,SuperSonics,1980-81,82,34,48,0.415,10,6,...,1167,2434,3601,1945,1986,628,1524,438,8531,20
6,1610612762,Utah,Jazz,1980-81,82,28,54,0.341,11,5,...,962,2325,3287,1948,2110,637,1423,386,8301,22
19,1610612764,Washington,Bullets,1980-81,82,39,43,0.476,7,4,...,1155,2533,3688,2151,1895,641,1422,392,8662,18
32,1610612765,Detroit,Pistons,1980-81,82,21,61,0.256,11,6,...,1201,2111,3312,1819,2125,884,1759,492,8174,23

Resets the index labels to 0 for a given season

First need number of 0's for set axis array, which is num rows

In [117]:
size_1980 = np.size(arr_1980.values,0)

In [118]:
arr_1980 = arr.groupby(['YEAR']).get_group('1980-81').set_axis(([0]*size_1980), axis='index', inplace=False)

In [120]:
arr_1980

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
0,1610612737,Atlanta,Hawks,1980-81,82,31,51,0.378,8,4,...,1201,2224,3425,1846,2276,749,1605,469,8604,19
0,1610612738,Boston,Celtics,1980-81,82,62,20,0.756,1,1,...,1155,2424,3579,2202,1990,683,1577,594,9008,8
0,1610612739,Cleveland,Cavaliers,1980-81,82,28,54,0.341,9,5,...,1258,2243,3501,2007,1995,632,1396,322,8670,17
0,1610612741,Chicago,Bulls,1980-81,82,45,37,0.549,5,2,...,1227,2475,3702,1925,2058,729,1672,514,8937,10
0,1610612742,Dallas,Mavericks,1980-81,82,15,67,0.183,12,6,...,1109,2177,3286,1984,2008,561,1439,214,8322,21
0,1610612743,Denver,Nuggets,1980-81,82,37,45,0.451,8,4,...,1325,2497,3822,2030,2108,720,1444,380,9986,1
0,1610612744,Golden State,Warriors,1980-81,82,39,43,0.476,7,4,...,1403,2366,3769,2026,2158,611,1547,301,9006,9
0,1610612745,Houston,Rockets,1980-81,82,40,42,0.488,5,2,...,1216,2347,3563,2099,1901,705,1451,390,8878,11
0,1610612746,San Diego,Clippers,1980-81,82,36,46,0.439,9,5,...,1169,2144,3313,2098,2078,764,1407,292,8737,16
0,1610612747,Los Angeles,Lakers,1980-81,82,54,28,0.659,3,2,...,1165,2491,3656,2363,1955,808,1557,551,9117,5
0,1610612749,Milwaukee,Bucks,1980-81,82,60,22,0.732,3,1,...,1261,2408,3669,2319,2198,862,1581,530,9276,2
0,1610612751,New Jersey,Nets,1980-81,82,24,58,0.293,10,5,...,1092,2374,3466,2068,2204,750,1664,458,8768,15
0,1610612752,New York,Knicks,1980-81,82,50,32,0.610,4,3,...,1137,2205,3342,1976,1917,861,1461,314,8849,12
0,1610612754,Indiana,Pacers,1980-81,82,44,38,0.537,6,3,...,1325,2267,3592,2091,2006,833,1491,484,8827,13
0,1610612755,Philadelphia,76ers,1980-81,82,62,20,0.756,1,1,...,1091,2618,3709,2369,2061,857,1702,591,9156,4
0,1610612756,Phoenix,Suns,1980-81,82,57,25,0.695,1,1,...,1234,2490,3724,2205,1996,876,1733,416,9019,7
0,1610612757,Portland,Trail Blazers,1980-81,82,45,37,0.549,4,3,...,1243,2388,3631,2244,2034,769,1518,480,9080,6
0,1610612758,Kansas City,Kings,1980-81,82,40,42,0.488,5,2,...,1037,2450,3487,2271,2092,719,1448,385,8769,14
0,1610612759,San Antonio,Spurs,1980-81,82,52,30,0.634,2,1,...,1304,2582,3886,2048,2114,685,1533,643,9209,3
0,1610612760,Seattle,SuperSonics,1980-81,82,34,48,0.415,10,6,...,1167,2434,3601,1945,1986,628,1524,438,8531,20
0,1610612762,Utah,Jazz,1980-81,82,28,54,0.341,11,5,...,962,2325,3287,1948,2110,637,1423,386,8301,22
0,1610612764,Washington,Bullets,1980-81,82,39,43,0.476,7,4,...,1155,2533,3688,2151,1895,641,1422,392,8662,18
0,1610612765,Detroit,Pistons,1980-81,82,21,61,0.256,11,6,...,1201,2111,3312,1819,2125,884,1759,492,8174,23

Access a specific column for every team

In [121]:
arr_1980.at[0,'WINS']

array([31, 62, 28, 45, 15, 37, 39, 40, 36, 54, 60, 24, 50, 44, 62, 57, 45,
       40, 52, 34, 28, 39, 21])

This is the first year each team was active

In [84]:
arr.at[0, 'YEAR']

array(['1949-50', '1946-47', '1970-71', '2002-03', '1966-67', '1980-81',
       '1976-77', '1946-47', '1967-68', '1970-71', '1948-49', '1988-89',
       '1968-69', '1989-90', '1976-77', '1946-47', '1989-90', '1976-77',
       '1949-50', '1968-69', '1970-71', '1948-49', '1976-77', '1967-68',
       '1995-96', '1974-75', '1995-96', '1961-62', '1948-49', '1988-89'],
      dtype=object)

This line gets the third team in team_arr, acceses its dataframe, and does.loc, which gets the 7th row

In [39]:
team_arr[2][0].loc[[7]] #Cavs in 1997

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
7,1610612739,Cleveland,Cavaliers,1977-78,82,43,39,0.524,4,3,...,1187,2676,3863,1740,1832,692,1382,455,8561,19

Test on appending dataframes and then accessing a certain row. Issue is the years are not the same as the teams started in different years

In [46]:
team_arr[0][0].append(team_arr[1][0], ignore_index=False).loc[[29]]

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
29,1610612737,Atlanta,Hawks,1978-79,82,46,36,0.561,5,3,...,1381,2341,3722,1938,2424,801,1523,596,8950,12
29,1610612738,Boston,Celtics,1975-76,82,54,28,0.659,1,1,...,1369,2972,4341,1980,2002,561,1609,260,8708,6

Accessing the first team's Pt rank in the second year they were active

In [40]:
team_arr[0][0].at[1, 'PTS_RANK']

3

In [44]:
team_arr[1][0]

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
0,1610612738,Boston,Celtics,1946-47,60,22,38,0.367,0,5,...,0,0,0,470,1202,0,0,0,3605,11
1,1610612738,Boston,Celtics,1947-48,48,20,28,0.417,0,3,...,0,0,0,364,1065,0,0,0,3303,8
2,1610612738,Boston,Celtics,1948-49,60,25,35,0.417,0,5,...,0,0,0,1135,1382,0,0,0,4593,9
3,1610612738,Boston,Celtics,1949-50,68,22,46,0.324,0,6,...,0,0,0,1473,1644,0,0,0,5420,7
4,1610612738,Boston,Celtics,1950-51,69,39,30,0.565,0,2,...,0,0,0,1579,1881,0,0,0,5881,1
5,1610612738,Boston,Celtics,1951-52,66,39,27,0.591,0,2,...,0,0,0,1606,1734,0,0,0,6027,1
6,1610612738,Boston,Celtics,1952-53,71,46,25,0.648,0,3,...,0,0,0,1666,1911,0,0,0,6258,1
7,1610612738,Boston,Celtics,1953-54,72,42,30,0.583,0,2,...,0,0,0,1773,1969,0,0,0,6315,1
8,1610612738,Boston,Celtics,1954-55,72,36,36,0.500,0,3,...,0,0,0,1905,1859,0,0,0,7305,1
9,1610612738,Boston,Celtics,1955-56,72,39,33,0.542,0,2,...,0,0,0,1834,1874,0,0,0,7632,1
10,1610612738,Boston,Celtics,1956-57,72,44,28,0.611,0,1,...,0,0,0,1464,1851,0,0,0,7599,1
11,1610612738,Boston,Celtics,1957-58,72,49,23,0.681,0,1,...,0,0,0,1508,1723,0,0,0,7916,2
12,1610612738,Boston,Celtics,1958-59,72,52,20,0.722,0,1,...,0,0,0,1568,1769,0,0,0,8379,1
13,1610612738,Boston,Celtics,1959-60,75,59,16,0.787,0,1,...,0,0,0,1849,1856,0,0,0,9337,1
14,1610612738,Boston,Celtics,1960-61,79,57,22,0.722,0,1,...,0,0,0,1872,2032,0,0,0,9456,3
15,1610612738,Boston,Celtics,1961-62,80,60,20,0.750,0,1,...,0,0,0,2049,1909,0,0,0,9687,3
16,1610612738,Boston,Celtics,1962-63,80,58,22,0.725,0,1,...,0,0,0,1960,2090,0,0,0,9504,3
17,1610612738,Boston,Celtics,1963-64,80,59,21,0.738,0,1,...,0,0,0,1760,2125,0,0,0,9042,2
18,1610612738,Boston,Celtics,1964-65,80,62,18,0.775,0,1,...,0,0,0,1772,2065,0,0,0,9024,3
19,1610612738,Boston,Celtics,1965-66,80,54,26,0.675,0,2,...,0,0,0,1795,2012,0,0,0,9014,7
20,1610612738,Boston,Celtics,1966-67,81,60,21,0.741,0,2,...,0,0,0,1962,2138,0,0,0,9664,4
21,1610612738,Boston,Celtics,1967-68,82,54,28,0.659,0,2,...,0,0,0,1798,2147,0,0,0,9523,8
22,1610612738,Boston,Celtics,1968-69,82,48,34,0.585,0,4,...,0,0,0,1953,2073,0,0,0,9102,10
23,1610612738,Boston,Celtics,1969-70,82,34,48,0.415,0,6,...,0,0,0,1875,2320,0,0,0,9422,11
24,1610612738,Boston,Celtics,1970-71,82,44,38,0.537,5,3,...,0,0,0,2052,2138,0,0,0,9608,2
25,1610612738,Boston,Celtics,1971-72,82,56,26,0.683,1,1,...,0,0,0,2230,2030,0,0,0,9477,3
26,1610612738,Boston,Celtics,1972-73,82,68,14,0.829,1,1,...,0,0,0,2320,1805,0,0,0,9238,2
27,1610612738,Boston,Celtics,1973-74,82,56,26,0.683,1,1,...,1378,3074,4452,2187,1868,561,1796,305,8937,4
28,1610612738,Boston,Celtics,1974-75,82,60,22,0.732,1,1,...,1315,2949,4264,2159,1913,662,1625,288,8734,3
29,1610612738,Boston,Celtics,1975-76,82,54,28,0.659,1,1,...,1369,2972,4341,1980,2002,561,1609,260,8708,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,1610612738,Boston,Celtics,1989-90,82,52,30,0.634,4,2,...,1066,2707,3773,2423,1717,539,1256,455,9023,8
44,1610612738,Boston,Celtics,1990-91,82,56,26,0.683,2,1,...,1088,2697,3785,2160,1695,672,1320,565,9145,6
45,1610612738,Boston,Celtics,1991-92,82,51,31,0.622,2,1,...,1095,2583,3678,2072,1686,636,1165,484,8745,9
46,1610612738,Boston,Celtics,1992-93,82,48,34,0.585,4,2,...,1076,2436,3512,1999,1862,647,1174,458,8502,19
47,1610612738,Boston,Celtics,1993-94,82,32,50,0.390,10,5,...,1037,2380,3417,1928,1849,674,1242,440,8267,16
48,1610612738,Boston,Celtics,1994-95,82,35,47,0.427,8,3,...,1156,2320,3476,1783,1975,612,1305,361,8428,11
49,1610612738,Boston,Celtics,1995-96,82,33,49,0.402,11,5,...,1050,2427,3477,1792,2041,653,1302,406,8495,5
50,1610612738,Boston,Celtics,1996-97,82,15,67,0.183,15,7,...,1095,2188,3283,1792,1915,810,1342,315,8248,5
51,1610612738,Boston,Celtics,1997-98,82,36,46,0.439,12,6,...,1196,2044,3240,1816,2203,987,1330,366,7864,14
52,1610612738,Boston,Celtics,1998-99,50,19,31,0.380,12,5,...,680,1458,2138,1073,1193,453,807,255,4650,10
53,1610612738,Boston,Celtics,1999-00,82,35,47,0.427,10,5,...,1108,2420,3528,1741,2223,795,1259,286,8146,9
54,1610612738,Boston,Celtics,2000-01,82,36,46,0.439,9,5,...,897,2367,3264,1708,1952,769,1285,336,7759,16
55,1610612738,Boston,Celtics,2001-02,82,49,33,0.598,3,2,...,891,2570,3461,1722,1776,793,1114,292,7901,12
56,1610612738,Boston,Celtics,2002-03,82,44,38,0.537,6,3,...,849,2471,3320,1575,1758,720,1147,303,7599,22
57,1610612738,Boston,Celtics,2003-04,82,36,46,0.439,8,4,...,851,2440,3291,1683,1837,770,1332,331,7811,8
58,1610612738,Boston,Celtics,2004-05,82,45,37,0.549,4,1,...,909,2438,3347,1810,2000,667,1297,423,8304,5
59,1610612738,Boston,Celtics,2005-06,82,33,49,0.402,11,3,...,813,2432,3245,1716,2033,578,1359,422,8033,12
60,1610612738,Boston,Celtics,2006-07,82,24,58,0.293,15,5,...,918,2391,3309,1630,1971,589,1350,382,7857,22
61,1610612738,Boston,Celtics,2007-08,82,66,16,0.805,1,1,...,830,2615,3445,1833,1864,696,1246,379,8245,11
62,1610612738,Boston,Celtics,2008-09,82,62,20,0.756,2,1,...,869,2586,3455,1862,1897,621,1280,387,8275,11
63,1610612738,Boston,Celtics,2009-10,82,50,32,0.610,4,1,...,716,2449,3165,1930,1816,701,1219,402,8136,19
64,1610612738,Boston,Celtics,2010-11,82,56,26,0.683,3,1,...,639,2542,3181,1921,1678,676,1195,344,7913,23
65,1610612738,Boston,Celtics,2011-12,66,39,27,0.591,4,1,...,509,2051,2560,1557,1315,498,979,362,6062,26
66,1610612738,Boston,Celtics,2012-13,81,41,40,0.506,7,3,...,654,2533,3187,1843,1717,667,1181,365,7818,20
67,1610612738,Boston,Celtics,2013-14,82,25,57,0.305,12,4,...,980,2505,3485,1726,1743,584,1261,343,7892,26
68,1610612738,Boston,Celtics,2014-15,82,40,42,0.488,7,2,...,910,2685,3595,2009,1738,674,1133,294,8312,13
69,1610612738,Boston,Celtics,2015-16,82,48,34,0.585,5,2,...,950,2733,3683,1981,1796,752,1127,348,8669,5
70,1610612738,Boston,Celtics,2016-17,82,53,29,0.646,1,1,...,743,2698,3441,2069,1686,617,1088,340,8857,7
71,1610612738,Boston,Celtics,2017-18,82,55,27,0.671,2,2,...,767,2878,3645,1842,1618,604,1148,373,8529,20
72,1610612738,Boston,Celtics,2018-19,82,49,33,0.598,4,3,...,804,2849,3653,2155,1670,706,1052,435,9216,14

In [6]:
from nba_api.stats.endpoints import commonplayerinfo

In [7]:
player_info = commonplayerinfo.CommonPlayerInfo(player_id=2544)
player_info.player_headline_stats.get_data_frame()

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

Only shows basic stats (not very helpful).

In [57]:
from nba_api.stats.endpoints import playercareerstats

In [81]:
career = playercareerstats.PlayerCareerStats(player_id='2544')
career.get_data_frames()[0]
# career.season_totals_regular_season.get_dict()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505

In [71]:
career.get_dict()
# nba_players = players.get_players()
# for player in nba_players:
#     career = playercareerstats.PlayerCareerStats(player_id=player["id"])

{'resource': 'playercareerstats',
 'parameters': {'PerMode': 'Totals', 'PlayerID': 2544, 'LeagueID': None},
 'resultSets': [{'name': 'SeasonTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[2544,
     '2003-04',
     '00',
     1610612739,
     'CLE',
     19.0,
     79,
     79,
     3120.0,
     622,
     1492,
     0.417,
     63,
     217,
     0.29,
     347,
     460,
     0.754,
     99,
     333,
     432,
     465,
     130,
     58,
     273,
     149,
     1654],
    [2544,
     '2004-05',
     '00',
     1610612739,
     'CLE',
     20.0,
     80,
     80,
     3388.0,
     795,
     1684,
     0.472,
     108,
     308,
     0.351,
     477,
     636,
     0.75,
     111,
     477,
     588,
     577,
     177,
     52,
     262,
     146,
     2175],
    [2544,
     '2005-06',
     '00',
     1610612739,
     'CLE',
     21.0,
     79,
     79,
     3361.0,
     875,
     1823,
     0.48,
     127,
     379,
     0.335,
     601,
     814,
     0.738,
     75,
     481,
     556,
     521,
     123,
     66,
     260,
     181,
     2478],
    [2544,
     '2006-07',
     '00',
     1610612739,
     'CLE',
     22.0,
     78,
     78,
     3190.0,
     772,
     1621,
     0.476,
     99,
     310,
     0.319,
     489,
     701,
     0.698,
     83,
     443,
     526,
     470,
     125,
     55,
     250,
     171,
     2132],
    [2544,
     '2007-08',
     '00',
     1610612739,
     'CLE',
     23.0,
     75,
     74,
     3027.0,
     794,
     1642,
     0.484,
     113,
     359,
     0.315,
     549,
     771,
     0.712,
     133,
     459,
     592,
     539,
     138,
     81,
     255,
     165,
     2250],
    [2544,
     '2008-09',
     '00',
     1610612739,
     'CLE',
     24.0,
     81,
     81,
     3054.0,
     789,
     1613,
     0.489,
     132,
     384,
     0.344,
     594,
     762,
     0.78,
     106,
     507,
     613,
     587,
     137,
     93,
     241,
     139,
     2304],
    [2544,
     '2009-10',
     '00',
     1610612739,
     'CLE',
     25.0,
     76,
     76,
     2966.0,
     768,
     1528,
     0.503,
     129,
     387,
     0.333,
     593,
     773,
     0.767,
     71,
     483,
     554,
     651,
     125,
     77,
     261,
     119,
     2258],
    [2544,
     '2010-11',
     '00',
     1610612748,
     'MIA',
     26.0,
     79,
     79,
     3063.0,
     758,
     1485,
     0.51,
     92,
     279,
     0.33,
     503,
     663,
     0.759,
     80,
     510,
     590,
     554,
     124,
     50,
     284,
     163,
     2111],
    [2544,
     '2011-12',
     '00',
     1610612748,
     'MIA',
     27.0,
     62,
     62,
     2326.0,
     621,
     1169,
     0.531,
     54,
     149,
     0.362,
     387,
     502,
     0.771,
     94,
     398,
     492,
     387,
     115,
     50,
     213,
     96,
     1683],
    [2544,
     '2012-13',
     '00',
     1610612748,
     'MIA',
     28.0,
     76,
     76,
     2877.0,
     765,
     1354,
     0.565,
     103,
     254,
     0.406,
     403,
     535,
     0.753,
     97,
     513,
     610,
     551,
     129,
     67,
     226,
     110,
     2036],
    [2544,
     '2013-14',
     '00',
     1610612748,
     'MIA',
     29.0,
     77,
     77,
     2902.0,
     767,
     1353,
     0.567,
     116,
     306,
     0.379,
     439,
     585,
     0.75,
     81,
     452,
     533,
     488,
     121,
     26,
     270,
     126,
     2089],
    [2544,
     '2014-15',
     '00',
     1610612739,
     'CLE',
     30.0,
     69,
     69,
     2493.0,
     624,
     1279,
     0.488,
     120,
     339,
     0.354,
     375,
     528,
     0.71,
     51,
     365,
     416,
     511,
     109,
     49,
     272,
     135,
     1743],
    [2544,
     '2015-16',
     '00',
     1610612739,
     'CLE',
     31.0,
     76,
     76,
     2709.0,
     737,
     1416,
     0.52,
     87,
     282,
     0.309,
     359,
     491,
     0.731,
     111,
     454,
     565,
     514,
     104,
     49,
     249,
     143,
     1920],
    [2544,
     '2016-17',
     '00',
     1610612739,
     'CLE',
     32.0,
     74,
     74,
     2795.0,
     736,
     1344,
     0.548,
     124,
     342,
     0.363,
     358,
     531,
     0.674,
     97,
     542,
     639,
     646,
     92,
     44,
     303,
     134,
     1954],
    [2544,
     '2017-18',
     '00',
     1610612739,
     'CLE',
     33.0,
     82,
     82,
     3026.0,
     857,
     1580,
     0.542,
     149,
     406,
     0.367,
     388,
     531,
     0.731,
     97,
     612,
     709,
     747,
     116,
     71,
     347,
     136,
     2251],
    [2544,
     '2018-19',
     '00',
     1610612747,
     'LAL',
     34.0,
     55,
     55,
     1937.0,
     558,
     1095,
     0.51,
     111,
     327,
     0.339,
     278,
     418,
     0.665,
     57,
     408,
     465,
     454,
     72,
     33,
     197,
     94,
     1505]]},
  {'name': 'CareerTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[2544,
     '00',
     0,
     1198,
     1197,
     46233.0,
     11838,
     23478,
     0.504216,
     1727,
     5028,
     0.343476,
     7140,
     9701,
     0.736006,
     1443,
     7437,
     8880,
     8662,
     1937,
     921,
     4163,
     2207,
     32543]]},
  {'name': 'SeasonTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[2544,
     '2005-06',
     '00',
     1610612739,
     'CLE',
     21.0,
     13,
     13,
     604.0,
     146,
     307,
     0.476,
     21,
     63,
     0.333,
     87,
     118,
     0.737,
     22,
     83,
     105,
     76,
     18,
     9,
     65,
     44,
     400],
    [2544,
     '2006-07',
     '00',
     1610612739,
     'CLE',
     22.0,
     20,
     20,
     893.0,
     166,
     399,
     0.416,
     21,
     75,
     0.28,
     148,
     196,
     0.755,
     26,
     135,
     161,
     159,
     34,
     10,
     66,
     40,
     501],
    [2544,
     '2007-08',
     '00',
     1610612739,
     'CLE',
     23.0,
     13,
     13,
     552.0,
     113,
     275,
     0.411,
     18,
     70,
     0.257,
     122,
     167,
     0.731,
     16,
     86,
     102,
     99,
     23,
     17,
     54,
     33,
     366],
    [2544,
     '2008-09',
     '00',
     1610612739,
     'CLE',
     24.0,
     14,
     14,
     580.0,
     159,
     312,
     0.51,
     27,
     81,
     0.333,
     149,
     199,
     0.749,
     19,
     109,
     128,
     102,
     23,
     12,
     38,
     30,
     494],
    [2544,
     '2009-10',
     '00',
     1610612739,
     'CLE',
     25.0,
     11,
     11,
     460.0,
     106,
     211,
     0.502,
     20,
     50,
     0.4,
     88,
     120,
     0.733,
     15,
     87,
     102,
     84,
     19,
     20,
     42,
     23,
     320],
    [2544,
     '2010-11',
     '00',
     1610612748,
     'MIA',
     26.0,
     21,
     21,
     922.0,
     174,
     373,
     0.466,
     30,
     85,
     0.353,
     119,
     156,
     0.763,
     34,
     142,
     176,
     123,
     35,
     25,
     66,
     56,
     497],
    [2544,
     '2011-12',
     '00',
     1610612748,
     'MIA',
     27.0,
     23,
     23,
     983.0,
     251,
     502,
     0.5,
     22,
     85,
     0.259,
     173,
     234,
     0.739,
     54,
     170,
     224,
     129,
     43,
     16,
     81,
     47,
     697],
    [2544,
     '2012-13',
     '00',
     1610612748,
     'MIA',
     28.0,
     23,
     23,
     960.0,
     212,
     432,
     0.491,
     36,
     96,
     0.375,
     136,
     175,
     0.777,
     37,
     156,
     193,
     152,
     41,
     18,
     70,
     43,
     596],
    [2544,
     '2013-14',
     '00',
     1610612748,
     'MIA',
     29.0,
     20,
     20,
     763.0,
     192,
     340,
     0.565,
     35,
     86,
     0.407,
     129,
     160,
     0.806,
     14,
     127,
     141,
     95,
     36,
     11,
     61,
     46,
     548],
    [2544,
     '2014-15',
     '00',
     1610612739,
     'CLE',
     30.0,
     20,
     20,
     844.0,
     227,
     544,
     0.417,
     25,
     110,
     0.227,
     122,
     167,
     0.731,
     37,
     189,
     226,
     169,
     33,
     21,
     82,
     58,
     601],
    [2544,
     '2015-16',
     '00',
     1610612739,
     'CLE',
     31.0,
     21,
     21,
     822.0,
     219,
     417,
     0.525,
     32,
     94,
     0.34,
     82,
     124,
     0.661,
     42,
     158,
     200,
     160,
     49,
     27,
     75,
     54,
     552],
    [2544,
     '2016-17',
     '00',
     1610612739,
     'CLE',
     32.0,
     18,
     18,
     744.0,
     217,
     384,
     0.565,
     44,
     107,
     0.411,
     113,
     162,
     0.698,
     19,
     145,
     164,
     141,
     35,
     23,
     72,
     43,
     591],
    [2544,
     '2017-18',
     '00',
     1610612739,
     'CLE',
     33.0,
     22,
     22,
     922.0,
     275,
     510,
     0.539,
     39,
     114,
     0.342,
     159,
     213,
     0.746,
     31,
     169,
     200,
     198,
     30,
     23,
     94,
     52,
     748]]},
  {'name': 'CareerTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[2544,
     '00',
     0,
     239,
     239,
     10050.0,
     2457,
     5006,
     0.490811,
     370,
     1116,
     0.331541,
     1627,
     2191,
     0.742583,
     366,
     1756,
     2122,
     1687,
     419,
     232,
     866,
     569,
     6911]]},
  {'name': 'SeasonTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[2544,
     '2004-05',
     '00',
     1610616833,
     'EST',
     20.0,
     1,
     1,
     31.0,
     6,
     13,
     0.462,
     1,
     4,
     0.25,
     0,
     1,
     0.0,
     1,
     7,
     8,
     6,
     2,
     0,
     3,
     0,
     13],
    [2544,
     '2005-06',
     '00',
     1610616833,
     'EST',
     21.0,
     1,
     1,
     31.0,
     12,
     21,
     0.571,
     4,
     10,
     0.4,
     1,
     5,
     0.2,
     2,
     4,
     6,
     2,
     2,
     0,
     1,
     2,
     29],
    [2544,
     '2006-07',
     '00',
     1610616833,
     'EST',
     22.0,
     1,
     1,
     32.0,
     11,
     20,
     0.55,
     4,
     8,
     0.5,
     2,
     2,
     1.0,
     0,
     6,
     6,
     6,
     1,
     0,
     4,
     0,
     28],
    [2544,
     '2007-08',
     '00',
     1610616833,
     'EST',
     23.0,
     1,
     1,
     30.0,
     12,
     22,
     0.545,
     2,
     7,
     0.286,
     1,
     1,
     1.0,
     1,
     7,
     8,
     9,
     2,
     2,
     4,
     3,
     27],
    [2544,
     '2008-09',
     '00',
     1610616833,
     'EST',
     24.0,
     1,
     1,
     27.0,
     8,
     19,
     0.421,
     2,
     5,
     0.4,
     2,
     2,
     1.0,
     0,
     5,
     5,
     3,
     0,
     0,
     3,
     0,
     20],
    [2544,
     '2009-10',
     '00',
     1610616833,
     'EST',
     25.0,
     1,
     1,
     32.0,
     10,
     22,
     0.455,
     1,
     6,
     0.167,
     4,
     4,
     1.0,
     1,
     4,
     5,
     6,
     4,
     0,
     2,
     1,
     25],
    [2544,
     '2010-11',
     '00',
     1610616833,
     'EST',
     26.0,
     1,
     1,
     32.0,
     10,
     18,
     0.556,
     0,
     3,
     0.0,
     9,
     10,
     0.9,
     2,
     10,
     12,
     10,
     0,
     0,
     4,
     3,
     29],
    [2544,
     '2011-12',
     '00',
     1610616833,
     'EST',
     27.0,
     1,
     1,
     32.0,
     15,
     23,
     0.652,
     6,
     8,
     0.75,
     0,
     0,
     0.0,
     0,
     6,
     6,
     7,
     0,
     0,
     4,
     2,
     36],
    [2544,
     '2012-13',
     '00',
     1610616833,
     'EST',
     28.0,
     1,
     1,
     30.0,
     7,
     18,
     0.389,
     3,
     7,
     0.429,
     2,
     4,
     0.5,
     0,
     3,
     3,
     5,
     1,
     0,
     4,
     0,
     19],
    [2544,
     '2013-14',
     '00',
     1610616833,
     'EST',
     29.0,
     1,
     1,
     33.0,
     11,
     22,
     0.5,
     0,
     7,
     0.0,
     0,
     0,
     0.0,
     1,
     6,
     7,
     7,
     3,
     0,
     1,
     0,
     22],
    [2544,
     '2014-15',
     '00',
     1610616833,
     'EST',
     30.0,
     1,
     1,
     32.0,
     11,
     21,
     0.524,
     4,
     12,
     0.333,
     4,
     5,
     0.8,
     1,
     4,
     5,
     7,
     2,
     0,
     4,
     1,
     30],
    [2544,
     '2015-16',
     '00',
     1610616833,
     'EST',
     31.0,
     1,
     1,
     20.0,
     6,
     13,
     0.462,
     1,
     5,
     0.2,
     0,
     0,
     0.0,
     0,
     4,
     4,
     7,
     0,
     0,
     4,
     0,
     13],
    [2544,
     '2016-17',
     '00',
     1610616833,
     'EST',
     32.0,
     1,
     1,
     19.0,
     10,
     17,
     0.588,
     3,
     8,
     0.375,
     0,
     0,
     0.0,
     0,
     3,
     3,
     1,
     0,
     0,
     4,
     2,
     23],
    [2544,
     '2017-18',
     '00',
     1610616833,
     'LBN',
     33.0,
     1,
     1,
     31.0,
     12,
     17,
     0.706,
     4,
     8,
     0.5,
     1,
     1,
     1.0,
     0,
     10,
     10,
     8,
     1,
     0,
     5,
     2,
     29],
    [2544,
     '2018-19',
     '00',
     1610616834,
     'LBN',
     34.0,
     1,
     1,
     27.0,
     9,
     17,
     0.529,
     1,
     8,
     0.125,
     0,
     1,
     0.0,
     2,
     6,
     8,
     4,
     0,
     2,
     1,
     1,
     19]]},
  {'name': 'CareerTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[2544,
     '00',
     0,
     15,
     15,
     440.0,
     150,
     283,
     0.530035,
     36,
     106,
     0.339622,
     26,
     36,
     0.722222,
     11,
     85,
     96,
     88,
     18,
     4,
     48,
     17,
     362]]},
  {'name': 'SeasonTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'SCHOOL_NAME',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonRankingsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[2544,
     '2003-04',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     9,
     7,
     4,
     90,
     83,
     60,
     92,
     22,
     15,
     73,
     103,
     56,
     65,
     13,
     14,
     59,
     3,
     8,
     23],
    [2544,
     '2004-05',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     1,
     1,
     2,
     37,
     35,
     35,
     71,
     10,
     10,
     98,
     90,
     21,
     29,
     5,
     2,
     71,
     5,
     2,
     2],
    [2544,
     '2005-06',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     2,
     2,
     2,
     39,
     28,
     19,
     93,
     6,
     3,
     94,
     144,
     19,
     32,
     10,
     16,
     44,
     6,
     2,
     2],
    [2544,
     '2006-07',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     1,
     2,
     2,
     35,
     55,
     33,
     102,
     5,
     3,
     116,
     122,
     25,
     39,
     12,
     12,
     57,
     7,
     2,
     6],
    [2544,
     '2007-08',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     14,
     1,
     2,
     41,
     48,
     27,
     113,
     5,
     3,
     111,
     56,
     27,
     33,
     10,
     6,
     40,
     6,
     2,
     1],
    [2544,
     '2008-09',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     7,
     3,
     4,
     34,
     25,
     18,
     109,
     1,
     3,
     93,
     88,
     14,
     25,
     8,
     7,
     25,
     4,
     2,
     1],
    [2544,
     '2009-10',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     12,
     2,
     3,
     26,
     25,
     17,
     109,
     2,
     3,
     82,
     135,
     23,
     39,
     6,
     11,
     39,
     5,
     2,
     1],
    [2544,
     '2010-11',
     '00',
     1610612748,
     'MIA',
     'NR',
     'NR',
     'NR',
     6,
     1,
     6,
     21,
     67,
     54,
     115,
     6,
     5,
     90,
     110,
     13,
     32,
     12,
     9,
     70,
     2,
     2,
     1],
    [2544,
     '2011-12',
     '00',
     1610612748,
     'MIA',
     'NR',
     'NR',
     'NR',
     10,
     2,
     4,
     11,
     96,
     100,
     72,
     2,
     2,
     79,
     81,
     17,
     26,
     12,
     4,
     51,
     6,
     2,
     1],
    [2544,
     '2012-13',
     '00',
     1610612748,
     'MIA',
     'NR',
     'NR',
     'NR',
     16,
     1,
     7,
     5,
     55,
     69,
     28,
     6,
     6,
     82,
     99,
     16,
     28,
     8,
     12,
     49,
     14,
     3,
     2],
    [2544,
     '2013-14',
     '00',
     1610612748,
     'MIA',
     'NR',
     'NR',
     'NR',
     8,
     2,
     10,
     4,
     47,
     49,
     45,
     7,
     8,
     86,
     113,
     30,
     43,
     9,
     14,
     153,
     4,
     3,
     3],
    [2544,
     '2014-15',
     '00',
     1610612739,
     'CLE',
     'NR',
     'NR',
     'NR',
     30,
     7,
     8,
     26,
     38,
     34,
     61,
     5,
     4,

In [82]:
from nba_api.stats.endpoints import commonteamroster

In [88]:
cr = commonteamroster.CommonTeamRoster("1610612739", "2018-19")
cr.get_data_frames()[0]

,TeamID,SEASON,LeagueID,PLAYER,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID
0,1610612739,2018,00,Kevin Love,0,F-C,6-10,251,"SEP 07, 1988",30.0,10,UCLA,201567
1,1610612739,2018,00,Nik Stauskas,1,G,6-6,205,"OCT 07, 1993",25.0,4,Michigan,203917
2,1610612739,2018,00,Collin Sexton,2,G,6-2,190,"JAN 04, 1999",20.0,R,Alabama,1629012
3,1610612739,2018,00,Marquese Chriss,3,F,6-10,240,"JUL 02, 1997",21.0,2,Washington,1627737
4,1610612739,2018,00,Jaron Blossomgame,4,F,6-8,220,"SEP 16, 1993",25.0,R,Clemson,1628417
5,1610612739,2018,00,JR Smith,5,G-F,6-6,225,"SEP 09, 1985",33.0,14,No College,2747
6,1610612739,2018,00,Jordan Clarkson,8,G,6-5,194,"JUN 07, 1992",27.0,4,Missouri,203903
7,1610612739,2018,00,Channing Frye,9,F-C,7-0,255,"MAY 17, 1983",36.0,12,Arizona,101112
8,1610612739,2018,00,David Nwaba,12,G,6-4,219,"JAN 14, 1993",26.0,2,Cal Poly-Obispo,1628021
9,1610612739,2018,00,Tristan Thompson,13,C-F,6-10,238,"MAR 13, 1991",28.0,7,Texas,202684
10,1610612739,2018,00,Cedi Osman,16,F,6-8,215,"APR 08, 1995",24.0,1,,1626224
11,1610612739,2018,00,Matthew Dellavedova,18,G,6-4,200,"SEP 08, 1990",28.0,5,St. Mary's (CA),203521
12,1610612739,2018,00,Brandon Knight,20,G,6-3,195,"DEC 02, 1991",27.0,6,Kentucky,202688
13,1610612739,2018,00,Larry Nance Jr.,22,F,6-9,230,"JAN 01, 1993",26.0,3,Wyoming,1626204
14,1610612739,2018,00,John Henson,31,F,6-11,219,"DEC 28, 1990",28.0,6,North Carolina,203089
15,1610612739,2018,00,Deng Adel,32,F,6-7,200,"FEB 01, 1997",22.0,R,Louisville,1629061
16,1610612739,2018,00,Ante Zizic,41,C,6-11,254,"JAN 04, 1997",22.0,1,,1627790

In [2]:
from nba_api.stats.endpoints import teamyearbyyearstats

In [5]:
teamyearbyyearstats.TeamYearByYearStats(1610612739).get_data_frames()[0]

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
0,1610612739,Cleveland,Cavaliers,1970-71,82,15,67,0.183,8,4,...,0,0,0,2065,2114,0,0,0,8373,17
1,1610612739,Cleveland,Cavaliers,1971-72,82,23,59,0.280,7,4,...,0,0,0,2060,1936,0,0,0,8674,16
2,1610612739,Cleveland,Cavaliers,1972-73,82,32,50,0.390,6,4,...,0,0,0,2106,1941,0,0,0,8418,17
3,1610612739,Cleveland,Cavaliers,1973-74,82,29,53,0.354,7,4,...,1275,2492,3767,2048,1925,598,1545,293,8221,17
4,1610612739,Cleveland,Cavaliers,1974-75,82,40,42,0.488,5,3,...,1058,2502,3560,1903,1881,600,1462,348,8117,16
5,1610612739,Cleveland,Cavaliers,1975-76,82,49,33,0.598,2,1,...,1192,2588,3780,1844,1871,638,1330,397,8340,17
6,1610612739,Cleveland,Cavaliers,1976-77,82,43,39,0.524,6,4,...,1312,2563,3875,1845,1951,579,1356,472,8370,20
7,1610612739,Cleveland,Cavaliers,1977-78,82,43,39,0.524,4,3,...,1187,2676,3863,1740,1832,692,1382,455,8561,19
8,1610612739,Cleveland,Cavaliers,1978-79,82,30,52,0.366,8,4,...,1229,2256,3485,1796,2027,688,1376,334,8732,20
9,1610612739,Cleveland,Cavaliers,1979-80,82,37,45,0.451,8,4,...,1307,2381,3688,2108,1934,764,1370,342,9360,3
10,1610612739,Cleveland,Cavaliers,1980-81,82,28,54,0.341,9,5,...,1258,2243,3501,2007,1995,632,1396,322,8670,17
11,1610612739,Cleveland,Cavaliers,1981-82,82,15,67,0.183,11,6,...,1190,2170,3360,1871,2193,634,1319,357,8463,21
12,1610612739,Cleveland,Cavaliers,1982-83,82,23,59,0.280,10,5,...,1173,2414,3587,1738,2236,617,1538,290,7964,23
13,1610612739,Cleveland,Cavaliers,1983-84,82,28,54,0.341,9,4,...,1213,2388,3601,1930,2206,630,1332,375,8386,22
14,1610612739,Cleveland,Cavaliers,1984-85,82,36,46,0.439,8,4,...,1203,2445,3648,2096,2173,622,1387,472,8903,16
15,1610612739,Cleveland,Cavaliers,1985-86,82,29,53,0.354,9,5,...,1086,2455,3541,2064,2267,627,1411,436,8836,19
16,1610612739,Cleveland,Cavaliers,1986-87,82,31,51,0.378,9,6,...,1257,2420,3677,1912,1853,672,1619,559,8558,22
17,1610612739,Cleveland,Cavaliers,1987-88,82,42,40,0.512,5,4,...,1015,2289,3304,2070,1836,733,1439,526,8566,21
18,1610612739,Cleveland,Cavaliers,1988-89,82,57,25,0.695,3,2,...,1033,2475,3508,2260,1592,791,1323,586,8923,12
19,1610612739,Cleveland,Cavaliers,1989-90,82,42,40,0.512,7,4,...,1128,2380,3508,2106,1666,645,1243,512,8411,21
20,1610612739,Cleveland,Cavaliers,1990-91,82,33,49,0.402,9,6,...,1011,2329,3340,2240,1672,643,1281,450,8343,22
21,1610612739,Cleveland,Cavaliers,1991-92,82,57,25,0.695,4,2,...,1041,2450,3491,2260,1556,616,1073,621,8926,7
22,1610612739,Cleveland,Cavaliers,1992-93,82,54,28,0.659,3,2,...,929,2496,3425,2349,1580,615,1120,536,8832,8
23,1610612739,Cleveland,Cavaliers,1993-94,82,47,35,0.573,5,3,...,1090,2353,3443,2049,1701,705,1136,426,8296,12
24,1610612739,Cleveland,Cavaliers,1994-95,82,43,39,0.524,6,4,...,1045,2237,3282,1672,1694,630,1176,349,7417,27
25,1610612739,Cleveland,Cavaliers,1995-96,82,47,35,0.573,4,3,...,867,2055,2922,1818,1685,674,1073,340,7473,28
26,1610612739,Cleveland,Cavaliers,1996-97,82,42,40,0.512,9,5,...,911,2161,3072,1716,1885,655,1190,315,7180,29
27,1610612739,Cleveland,Cavaliers,1997-98,82,47,35,0.573,6,5,...,955,2331,3286,1894,1939,814,1421,419,7585,24
28,1610612739,Cleveland,Cavaliers,1998-99,50,22,28,0.440,11,7,...,472,1316,1788,1093,1208,452,785,203,4322,26
29,1610612739,Cleveland,Cavaliers,1999-00,82,32,50,0.390,11,6,...,1010,2499,3509,1941,2219,715,1427,363,7950,18
30,1610612739,Cleveland,Cavaliers,2000-01,82,30,52,0.366,11,6,...,1015,2440,3455,1708,1904,642,1350,436,7561,22
31,1610612739,Cleveland,Cavaliers,2001-02,82,29,53,0.354,14,7,...,968,2483,3451,1891,1752,572,1196,470,7812,16
32,1610612739,Cleveland,Cavaliers,2002-03,82,17,65,0.207,15,8,...,1118,2542,3660,1712,1864,636,1501,521,7495,25
33,1610612739,Cleveland,Cavaliers,2003-04,82,35,47,0.427,9,5,...,1118,2619,3737,1808,1743,585,1216,537,7619,14
34,1610612739,Cleveland,Cavaliers,2004-05,82,42,40,0.512,9,4,...,1117,2352,3469,1851,1850,654,1141,461,7914,17
35,1610612739,Cleveland,Cavaliers,2005-06,82,50,32,0.610,3,2,...,959,2511,3470,1560,1733,567,1137,392,8002,15
36,1610612739,Cleveland,Cavaliers,2006-07,82,50,32,0.610,2,2,...,1039,2529,3568,1708,1781,625,1177,353,7934,19
37,1610612739,Cleveland,Cavaliers,2007-08,82,45,37,0.549,4,2,...,1092,2563,3655,1640,1712,579,1145,427,7903,24
38,1610612739,Cleveland,Cavaliers,2008-09,82,66,16,0.805,1,1,...,886,2574,3460,1663,1663,593,1045,435,8223,13
39,1610612739,Cleveland,Cavaliers,2009-10,82,61,21,0.744,1,1,...,791,2692,3483,1835,1591,564,1137,425,8373,9
40,1610612739,Cleveland,Cavaliers,2010-11,82,19,63,0.232,15,5,...,856,2449,3305,1720,1648,544,1166,341,7827,25
41,1610612739,Cleveland,Cavaliers,2011-12,66,21,45,0.318,13,5,...,841,1949,2790,1308,1317,466,1017,262,6140,25
42,1610612739,Cleveland,Cavaliers,2012-13,82,24,58,0.293,13,5,...,1004,2359,3363,1694,1737,647,1149,334,7913,18
43,1610612739,Cleveland,Cavaliers,2013-14,82,33,49,0.402,10,3,...,989,2629,3618,1738,1640,579,1163,304,8054,22
44,1610612739,Cleveland,Cavaliers,2014-15,82,53,29,0.646,2,1,...,911,2612,3523,1814,1510,603,1171,340,8457,8
45,1610612739,Cleveland,Cavaliers,2015-16,82,57,25,0.695,1,1,...,873,2777,3650,1861,1666,551,1114,317,8555,8
46,1610612739,Cleveland,Cavaliers,2016-17,82,51,31,0.622,2,1,...,766,2821,3587,1858,1486,539,1121,327,9048,4
47,1610612739,Cleveland,Cavaliers,2017-18,82,50,32,0.610,4,1,...,694,2761,3455,1916,1524,582,1126,312,9091,5
48,1610612739,Cleveland,Cavaliers,2018-19,82,19,63,0.232,14,5,...,879,2619,3498,1698,1642,534,1106,195,8567,29